[[main]]
none = "none"

[[main]]
name = "Project"
pre = "codepen"
pageRef = "newSite"
identifier = "mjDbN4xP6v"
weight = 9999

[[main]]
name = "Game"
pre = "dribbble"
pageRef = "newSite"
identifier = "eHs9DV6fBg"
weight = 9999

[[main]]
name = "Music"
pre = "apple"
pageRef = "newSite"
identifier = "dz6sfeg70B"
weight = 9999

[[footer]]
none = "none"
