[[main]]
none = "none"

[[main]]
name = "project"
pre = "codepen"
pageRef = "newSite"
identifier = "o8JJ9pNntr"
weight = 9999

[[main]]
name = "game"
pre = "envelope"
url = "newSite"
identifier = "WwSHAumpGZ"
weight = 9999

[[main]]
name = "music"
pre = "bluesky"
pageRef = "newSite"
identifier = "n5wHZoymha"
weight = 9999

[[footer]]
none = "none"
