languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "首页"


[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.gif"
  secondaryLogo = "img/logo.png"
  description = "I'm Z, A Coder & Musician."
  copyright = "<span class='inline-block'> Z的枯燥生活 © { year } </span> <a href='https://beian.miit.gov.cn'>粤ICP备2024319385号-1</a></span>."


[params.author]
  name = " "
  image = "img/avatar.png"
 # headline = "于身为长物 于世为闲事"
  bio = "反者道之动"
  links = [
    { github = "https://github.com/bin549" },
    { itch-io = "https://bin549.itch.io" },
    { spotify = "https://learn.stem-powered.com/course/creator?id=11" },
    { ko-fi = "https://afdian.com/a/bin549" },
  ]

