version: '3.7'

services:
  hugo:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    ports:
      - "1313:1313"
    environment:
      - HUGO_ENV=development 
    command: ["hugo", "server", "--bind", "0.0.0.0", "--port", "1313"]

