version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro 
    environment:
      - HUGO_ENV=production
