version: '3.8'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro 
    environment:
      - HUGO_ENV=production
