FROM alpine:latest AS build

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk add --no-cache git hugo

WORKDIR /src

COPY . .

RUN hugo

FROM nginx:alpine

COPY --from=build /src/public /usr/share/nginx/html

EXPOSE 80